[patch]
title = "EXE4 BARELY ENGLISH"
authors = ["bigfarts <bigfarts@punymail.com>"]
license = "WTFPL"
source = "https://github.com/tangobattle/exe-barely-english-patches"

[versions.'0.0.0']
netplay_compatibility = "exe4"

[versions.'0.0.1']
netplay_compatibility = "exe4"
